esphome:
  name: "keller-heizung"
  friendly_name: Keller - Heizung

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XCHVEtKo+Vs+Cag4BJdt/eY3lgyi6nUvwdeT/aBLxVU="

ota:
  - platform: esphome
    password: "5e1eae63fc74f0d38e49b50252d1ced7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Keller-Heizung"
    password: "ldfkSXuPJ3bN"

captive_portal:

one_wire:
 - id: bus_one
   platform: gpio
   pin:
    number: GPIO12
    mode:
      input: true
      pullup: true
# 0x1e4163801e64ff28

 - id: bus_two
   platform: gpio
   pin:
    number: GPIO14
    mode:
      input: true
      pullup: false
  
   
# 0x4ea264851e64ff28

sensor:
  - platform: dallas_temp
    address: 0x1e4163801e64ff28
    one_wire_id: bus_one
    name: "Ruecklauf Fußbodenheizung"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-plus"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 10s
  - platform: dallas_temp
    address: 0x4ea264851e64ff28
    one_wire_id: bus_two
    name: "Vorlauf Fußbodenheizung"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-minus"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 5s

